-- Daily flight data update for 2025-06-22
-- Generated: 2025-07-21 13:09:22

SET AUTOCOMMIT = 0;
START TRANSACTION;

-- Remove existing data for 2025-06-22
DELETE FROM flights WHERE flight_date='2025-06-22';

-- Arrivals for 2025-06-22
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '746',
    'Ryanair',
    'FR',
    'RYR',
    'arrival',
    'landed',
    'Kastrup',
    'CPH',
    'EKCH',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Kastrup", "timezone": "Europe/Copenhagen", "iata": "CPH", "icao": "EKCH", "terminal": null, "gate": null, "delay": 59, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Ryanair", "iata": "FR", "icao": "RYR"}, "flight": {"number": "746", "iata": "FR746", "icao": "RYR746", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1836',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'scheduled',
    'Ibiza',
    'IBZ',
    'LEIB',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "scheduled", "departure": {"airport": "Ibiza", "timezone": "Europe/Madrid", "iata": "IBZ", "icao": "LEIB", "terminal": null, "gate": null, "delay": 72, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1836", "iata": "LS1836", "icao": "EXS1836", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1057',
    'Kenya Airways',
    'KQ',
    'KQA',
    'arrival',
    'landed',
    'Schiphol',
    'AMS',
    'EHAM',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    1,
    'eastern airways',
    't3',
    '1083',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Schiphol", "timezone": "Europe/Amsterdam", "iata": "AMS", "icao": "EHAM", "terminal": null, "gate": null, "delay": 21, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Kenya Airways", "iata": "KQ", "icao": "KQA"}, "flight": {"number": "1057", "iata": "KQ1057", "icao": "KQA1057", "codeshared": {"airline_name": "eastern airways", "airline_iata": "t3", "airline_icao": "eze", "flight_number": "1083", "flight_iata": "t31083", "flight_icao": "eze1083"}}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '230',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'scheduled',
    'Aldergrove International Airport',
    'BFS',
    'EGAA',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "scheduled", "departure": {"airport": "Aldergrove International Airport", "timezone": "Europe/London", "iata": "BFS", "icao": "EGAA", "terminal": null, "gate": null, "delay": 71, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "230", "iata": "U2230", "icao": "EZY230", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1850',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'landed',
    'Dalaman',
    'DLM',
    'LTBS',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Dalaman", "timezone": "Europe/Istanbul", "iata": "DLM", "icao": "LTBS", "terminal": null, "gate": null, "delay": 25, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1850", "iata": "LS1850", "icao": "EXS1850", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '210',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Glasgow International',
    'GLA',
    'EGPF',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Glasgow International", "timezone": "Europe/London", "iata": "GLA", "icao": "EGPF", "terminal": null, "gate": null, "delay": 14, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "210", "iata": "U2210", "icao": "EZY210", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2776',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Charles De Gaulle',
    'CDG',
    'LFPG',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Charles De Gaulle", "timezone": "Europe/Paris", "iata": "CDG", "icao": "LFPG", "terminal": null, "gate": null, "delay": 17, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2776", "iata": "U22776", "icao": "EZY2776", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2934',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Berlin Brandenburg Airport',
    'BER',
    'EDDB',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Berlin Brandenburg Airport", "timezone": "Europe/Berlin", "iata": "BER", "icao": "EDDB", "terminal": null, "gate": null, "delay": 6, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2934", "iata": "U22934", "icao": "EZY2934", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1848',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'scheduled',
    'Kos Island International Airport',
    'KGS',
    'LGKO',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "scheduled", "departure": {"airport": "Kos Island International Airport", "timezone": "Europe/Athens", "iata": "KGS", "icao": "LGKO", "terminal": null, "gate": null, "delay": 88, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1848", "iata": "LS1848", "icao": "EXS1848", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1864',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'landed',
    'Gran Canaria',
    'LPA',
    'GCLP',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Gran Canaria", "timezone": "Atlantic/Canary", "iata": "LPA", "icao": "GCLP", "terminal": null, "gate": null, "delay": 9, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1864", "iata": "LS1864", "icao": "EXS1864", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2770',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Mérignac',
    'BOD',
    'LFBD',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "M\\u00e9rignac", "timezone": "Europe/Paris", "iata": "BOD", "icao": "LFBD", "terminal": null, "gate": null, "delay": null, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2770", "iata": "U22770", "icao": "EZY2770", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '447',
    'Toyo Aviation',
    NULL,
    'TOY',
    'arrival',
    'scheduled',
    'Ibiza',
    'IBZ',
    'LEIB',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "scheduled", "departure": {"airport": "Ibiza", "timezone": "Europe/Madrid", "iata": "IBZ", "icao": "LEIB", "terminal": null, "gate": null, "delay": 59, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Toyo Aviation", "iata": null, "icao": "TOY"}, "flight": {"number": "447", "iata": null, "icao": "TOY447", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1804',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'landed',
    'Lanzarote',
    'ACE',
    'GCRR',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Lanzarote", "timezone": "Atlantic/Canary", "iata": "ACE", "icao": "GCRR", "terminal": null, "gate": null, "delay": 13, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1804", "iata": "LS1804", "icao": "EXS1804", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '242',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Newcastle Airport',
    'NCL',
    'EGNT',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Newcastle Airport", "timezone": "Europe/London", "iata": "NCL", "icao": "EGNT", "terminal": null, "gate": null, "delay": null, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "242", "iata": "U2242", "icao": "EZY242", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '220',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Edinburgh',
    'EDI',
    'EGPH',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Edinburgh", "timezone": "Europe/London", "iata": "EDI", "icao": "EGPH", "terminal": null, "gate": null, "delay": 38, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "220", "iata": "U2220", "icao": "EZY220", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2708',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Barajas',
    'MAD',
    'LEMD',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Barajas", "timezone": "Europe/Madrid", "iata": "MAD", "icao": "LEMD", "terminal": null, "gate": null, "delay": 14, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2708", "iata": "U22708", "icao": "EZY2708", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '6773',
    'TUIfly',
    'X3',
    'TUI',
    'arrival',
    'landed',
    'Ioannis Kapodistrias',
    'CFU',
    'LGKR',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Ioannis Kapodistrias", "timezone": "Europe/Athens", "iata": "CFU", "icao": "LGKR", "terminal": null, "gate": null, "delay": 29, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "TUIfly", "iata": "X3", "icao": "TUI"}, "flight": {"number": "6773", "iata": "X36773", "icao": "TUI6773", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1820',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'landed',
    'Kefalonia Istland International Airport',
    'EFL',
    'LGKF',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Kefalonia Istland International Airport", "timezone": "Europe/Athens", "iata": "EFL", "icao": "LGKF", "terminal": null, "gate": null, "delay": 81, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1820", "iata": "LS1820", "icao": "EXS1820", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2838',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Leonardo Da Vinci (Fiumicino)',
    'FCO',
    'LIRF',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Leonardo Da Vinci (Fiumicino)", "timezone": "Europe/Rome", "iata": "FCO", "icao": "LIRF", "terminal": null, "gate": null, "delay": 43, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2838", "iata": "U22838", "icao": "EZY2838", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '4756',
    'Ryanair',
    'FR',
    'RYR',
    'arrival',
    'landed',
    'Lanzarote',
    'ACE',
    'GCRR',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Lanzarote", "timezone": "Atlantic/Canary", "iata": "ACE", "icao": "GCRR", "terminal": null, "gate": null, "delay": 28, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Ryanair", "iata": "FR", "icao": "RYR"}, "flight": {"number": "4756", "iata": "FR4756", "icao": "RYR4756", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2706',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'El Prat De Llobregat',
    'BCN',
    'LEBL',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "El Prat De Llobregat", "timezone": "Europe/Madrid", "iata": "BCN", "icao": "LEBL", "terminal": null, "gate": null, "delay": 21, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2706", "iata": "U22706", "icao": "EZY2706", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '6747',
    'TUIfly',
    'X3',
    'TUI',
    'arrival',
    'landed',
    'Paphos International Airport',
    'PFO',
    'LCPH',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Paphos International Airport", "timezone": "Asia/Nicosia", "iata": "PFO", "icao": "LCPH", "terminal": null, "gate": null, "delay": 20, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "TUIfly", "iata": "X3", "icao": "TUI"}, "flight": {"number": "6747", "iata": "X36747", "icao": "TUI6747", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2874',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Faro',
    'FAO',
    'LPFR',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Faro", "timezone": "Europe/Lisbon", "iata": "FAO", "icao": "LPFR", "terminal": null, "gate": null, "delay": 12, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2874", "iata": "U22874", "icao": "EZY2874", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1812',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'landed',
    'Paphos International Airport',
    'PFO',
    'LCPH',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Paphos International Airport", "timezone": "Asia/Nicosia", "iata": "PFO", "icao": "LCPH", "terminal": null, "gate": null, "delay": 40, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1812", "iata": "LS1812", "icao": "EXS1812", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2950',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Agadir Almassira',
    'AGA',
    'GMAD',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Agadir Almassira", "timezone": "Africa/Casablanca", "iata": "AGA", "icao": "GMAD", "terminal": null, "gate": null, "delay": 39, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2950", "iata": "U22950", "icao": "EZY2950", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2858',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Antalya',
    'AYT',
    'LTAI',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Antalya", "timezone": "Europe/Istanbul", "iata": "AYT", "icao": "LTAI", "terminal": null, "gate": null, "delay": 53, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2858", "iata": "U22858", "icao": "EZY2858", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '2852',
    'easyJet',
    'U2',
    'EZY',
    'arrival',
    'landed',
    'Dalaman',
    'DLM',
    'LTBS',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Dalaman", "timezone": "Europe/Istanbul", "iata": "DLM", "icao": "LTBS", "terminal": null, "gate": null, "delay": 46, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "easyJet", "iata": "U2", "icao": "EZY"}, "flight": {"number": "2852", "iata": "U22852", "icao": "EZY2852", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '325',
    'TUIfly',
    'X3',
    'TUI',
    'arrival',
    'landed',
    'Hurghada',
    'HRG',
    'HEGN',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Hurghada", "timezone": "Africa/Cairo", "iata": "HRG", "icao": "HEGN", "terminal": null, "gate": null, "delay": 31, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "TUIfly", "iata": "X3", "icao": "TUI"}, "flight": {"number": "325", "iata": "X3325", "icao": "TUI325", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '1846',
    'Jet2',
    'LS',
    'EXS',
    'arrival',
    'landed',
    'Antalya',
    'AYT',
    'LTAI',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Antalya", "timezone": "Europe/Istanbul", "iata": "AYT", "icao": "LTAI", "terminal": null, "gate": null, "delay": 52, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "Jet2", "iata": "LS", "icao": "EXS"}, "flight": {"number": "1846", "iata": "LS1846", "icao": "EXS1846", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;
INSERT INTO flights (
    flight_date, flight_number, airline_name, airline_iata, airline_icao,
    flight_type, flight_status,
    origin_airport, origin_iata, origin_icao,
    destination_airport, destination_iata, destination_icao,
    scheduled_utc, estimated_utc, actual_utc,
    terminal, gate, delay_minutes, time_category,
    is_codeshare, codeshare_airline_name, codeshare_airline_iata, codeshare_flight_number,
    raw_data
) VALUES (
    '2025-06-22',
    '6759',
    'TUIfly',
    'X3',
    'TUI',
    'arrival',
    'landed',
    'Lanzarote',
    'ACE',
    'GCRR',
    'Bristol',
    'BRS',
    'EGGD',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    0,
    '',
    '',
    '',
    '{"flight_date": "2025-06-22", "flight_status": "landed", "departure": {"airport": "Lanzarote", "timezone": "Atlantic/Canary", "iata": "ACE", "icao": "GCRR", "terminal": null, "gate": null, "delay": 7, "scheduled": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "arrival": {"airport": "Bristol", "timezone": "Europe/London", "iata": "BRS", "icao": "EGGD", "terminal": null, "gate": null, "baggage": null, "scheduled": null, "delay": null, "estimated": null, "actual": null, "estimated_runway": null, "actual_runway": null}, "airline": {"name": "TUIfly", "iata": "X3", "icao": "TUI"}, "flight": {"number": "6759", "iata": "X36759", "icao": "TUI6759", "codeshared": null}, "aircraft": null, "live": null, "time_category": "Unknown"}'
) ON DUPLICATE KEY UPDATE
    flight_status=VALUES(flight_status),
    estimated_utc=VALUES(estimated_utc),
    actual_utc=VALUES(actual_utc),
    delay_minutes=VALUES(delay_minutes),
    time_category=VALUES(time_category),
    updated_at=CURRENT_TIMESTAMP;

-- Update daily summary for 2025-06-22
INSERT INTO daily_summary (
    flight_date, total_flights, total_arrivals, total_departures,
    night_flights, shoulder_flights, regular_flights, average_delay_minutes
) SELECT 
    '2025-06-22',
    COUNT(*),
    SUM(CASE WHEN flight_type='arrival' THEN 1 ELSE 0 END),
    SUM(CASE WHEN flight_type='departure' THEN 1 ELSE 0 END),
    SUM(CASE WHEN time_category='Night hour flights' THEN 1 ELSE 0 END),
    SUM(CASE WHEN time_category='Shoulder hour flights' THEN 1 ELSE 0 END),
    SUM(CASE WHEN time_category='Regular flights' THEN 1 ELSE 0 END),
    AVG(COALESCE(delay_minutes,0))
FROM flights WHERE flight_date='2025-06-22'
ON DUPLICATE KEY UPDATE
    total_flights=VALUES(total_flights),
    total_arrivals=VALUES(total_arrivals),
    total_departures=VALUES(total_departures),
    night_flights=VALUES(night_flights),
    shoulder_flights=VALUES(shoulder_flights),
    regular_flights=VALUES(regular_flights),
    average_delay_minutes=VALUES(average_delay_minutes),
    updated_at=CURRENT_TIMESTAMP;

COMMIT;
SET AUTOCOMMIT = 1;

-- Update completed: 30 flights for 2025-06-22
SELECT 'Daily update completed successfully!' AS status;